import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF43B02A);
const kPrimaryLightColor = Color(0xFF86BC25);

const textInputDecoration = InputDecoration(
  fillColor: Colors.white,
  filled: true,
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.white, width: 2.0),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.pink, width: 2.0),
  ),
);

// TODO die Logic vor dem 23.03.2022 war wahrscheinlich cleverer. Wichtig zu beachten vor nationaler Implementierung.
var ligacodes = [
  [
    'Baden',
    'Herren',
    'Oberliga',
    'Oberliga Baden-Württemberg',
    'oberliga-baden-wuerttemberg'
  ],
  [
    'Baden',
    'Herren',
    'Verbandsliga',
    'Verbandsliga Baden',
    'verbandsliga-baden-fb-1',
    'Landesliga Mittelbaden',
    'nordbaden-landesliga-mittelbaden-fb-1',
    'Landesliga Odenwald',
    'nordbaden-landesliga-odenwald-fb-1',
    'Landesliga Rhein-Neckar',
    'nordbaden-landesliga-rhein-neckar-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisliga',
    'Kreisliga Bruchsal',
    'kreisliga-bruchsal-fb-1',
    'Kreisliga Buchen',
    'kreisliga-buchen-fb-1',
    'Kreisliga Heidelberg',
    'kreisliga-heidelberg-fb-1',
    'Kreisliga Karlsruhe',
    'kreisliga-heidelberg-fb-1',
    'Kreisliga Mannheim',
    'kreisliga-mannheim-fb-1',
    'Kreisliga Mosbach',
    'kreisliga-mosbach-fb-1',
    'Kreisliga Pforzheim',
    'kreisliga-pforzheim-fb-1',
    'Kreisliga Sinsheim',
    'kreisliga-sinsheim-fb-1',
    'Kreisliga Tauberbischofsheim',
    'kreisliga-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse A',
    'Kreisklasse A Bruchsal',
    'kreisklasse-a-bruchsal-fb-1',
    'Kreisklasse A Buchen',
    'kreisklasse-a-buchen-fb-1',
    'Kreisklasse A Heidelberg',
    'kreisklasse-a-heidelberg-fb-1',
    'Kreisklasse A Karlsruhe 1',
    'kreisklasse-a-karlsruhe-1-fb-1',
    'Kreisklasse A Karlsruhe 2',
    'kreisklasse-a-karlsruhe-2-fb-1',
    'Kreisklasse A Mannheim 1',
    'kreisklasse-a-mannheim-1-fb-1',
    'Kreisklasse A Mannheim 2',
    'kreisklasse-a-mannheim-2-fb-1',
    'Kreisklasse A Mosbach',
    'kreisklasse-a-mosbach-fb-1',
    'Kreisklasse A Pforzheim 1',
    'kreisklasse-a-pforzheim-1-fb-1',
    'Kreisklasse A Pforzheim 2',
    'kreisklasse-a-pforzheim-2-fb-1',
    'Kreisklasse A Sinsheim',
    'kreisklasse-a-sinsheim-fb-1',
    'Kreisklasse A Tauberbischofsheim',
    'kreisklasse-a-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse B',
    'Kreisklasse B Bruchsal Hardt',
    'kreisklasse-b-bruchsal-hardt-fb-1',
    'Kreisklasse B Bruchsal Kraichgau',
    'nordbaden-kk-b-bruchsal-fb-1',
    'Kreisklasse B Buchen',
    'nordbaden-kk-b-buchen-1-fb-1',
    'Kreisklasse B Heidelberg',
    'nordbaden-kk-b-heidelberg-fb-1',
    'Kreisklasse B Karlsruhe 1',
    'nordbaden-kkb-karlsruhe-1-fb-1',
    'Kreisklasse B Karlsruhe 2',
    'nordbaden-kkb-karlsruhe-2-fb-1',
    'Kreisklasse B Karlsruhe 3',
    'nordbaden-kkb-karlsruhe-3-fb-1',
    'Kreisklasse B Mannheim 1',
    'nordbaden-kk-b-mannheim-1-fb-1',
    'Kreisklasse B Mannheim 2',
    'nordbaden-kk-b-mannheim-2-fb-1',
    'Kreisklasse B Mannheim 3',
    'nordbaden-kk-a-mannheim-3-fb-1',
    'Kreisklasse B Mosbach 1',
    'nordbaden-kk-b-mosbach-1-fb-1',
    'Kreisklasse B Mosbach 2',
    'nordbaden-kk-b-mosbach-2-fb-1',
    'Kreisklasse B Pforzheim 1',
    'nordbaden-kk-b-pforzheim-1-fb-1',
    'Kreisklasse B Pforzheim 2',
    'nordbaden-kk-b-pforzheim-2-fb-1',
    'Kreisklasse B Sinsheim 1',
    'nordbaden-kk-b-sinsheim-1-fb-1',
    'Kreisklasse B Sinsheim 2',
    'nordbaden-kk-b-sinsheim-2-fb-1',
    'Kreisklasse B Tauberbischofsheim',
    'nordbaden-kk-b-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse C',
    'Kreisklasse C Heidelberg Ost',
    'nordbaden-kreisklasse-c-heidelberg-ost-6710',
    'Kreisklasse C Heidelberg West',
    'nordbaden-kreisklasse-c-heidelberg-west-6709',
    'Kreisklasse C Karlsruhe 1',
    'nordbaden-kreisklasse-c-karlsruhe-1-6713',
    'Kreisklasse C Karlsruhe 2',
    'nordbaden-kreisklasse-c-karlsruhe-2-6714',
    'Kreisklasse C Karlsruhe 3',
    'nordbaden-kreisklasse-c-karlsruhe-3-6715',
    'Kreisklasse C Karlsruhe 4',
    'nordbaden-kreisklasse-c-karlsruhe-4-6716',
    'Kreisklasse C Mannheim 1',
    'nordbaden-kreisklasse-c-mannheim-1-6711',
    'Kreisklasse C Pforzheim 1',
    'nordbaden-kreisklasse-c-pforzheim-1-6718',
    'Kreisklasse C Pforzheim 2',
    'nordbaden-kreisklasse-c-pforzheim-2-6719',
    'Kreisklasse C Pforzheim 3',
    'nordbaden-kreisklasse-c-pforzheim-3-6720',
    'Kreisklasse C Tauberbischofsheim',
    'nordbaden-kreisklasse-c-tauberbischofsheim-1-6721'
  ],
];
