import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF43B02A);
const kPrimaryLightColor = Color(0xFF86BC25);

const textInputDecoration = InputDecoration(
  fillColor: Colors.white,
  filled: true,
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.white, width: 2.0),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.pink, width: 2.0),
  ),
);

// TODO die Logic vor dem 23.03.2022 war wahrscheinlich cleverer. Wichtig zu beachten vor nationaler Implementierung.
var ligacodes = [
  [
    'Baden',
    'Herren',
    'Oberliga',
    'Oberliga Baden-Württemberg',
    'oberliga-baden-wuerttemberg'
  ],
  [
    'Baden',
    'Herren',
    'Verbandsliga',
    'Verbandsliga Baden',
    'verbandsliga-baden-fb-1',
    'Landesliga Mittelbaden',
    'nordbaden-landesliga-mittelbaden-fb-1',
    'Landesliga Odenwald',
    'nordbaden-landesliga-odenwald-fb-1',
    'Landesliga Rhein-Neckar',
    'nordbaden-landesliga-rhein-neckar-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisliga',
    'Kreisliga Bruchsal',
    'kreisliga-bruchsal-fb-1',
    'Kreisliga Buchen',
    'kreisliga-buchen-fb-1',
    'Kreisliga Heidelberg',
    'kreisliga-heidelberg-fb-1',
    'Kreisliga Karlsruhe',
    'kreisliga-heidelberg-fb-1',
    'Kreisliga Mannheim',
    'kreisliga-mannheim-fb-1',
    'Kreisliga Mosbach',
    'kreisliga-mosbach-fb-1',
    'Kreisliga Pforzheim',
    'kreisliga-pforzheim-fb-1',
    'Kreisliga Sinsheim',
    'kreisliga-sinsheim-fb-1',
    'Kreisliga Tauberbischofsheim',
    'kreisliga-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse A',
    'Kreisklasse A Bruchsal',
    'kreisklasse-a-bruchsal-fb-1',
    'Kreisklasse A Buchen',
    'kreisklasse-a-buchen-fb-1',
    'Kreisklasse A Heidelberg',
    'kreisklasse-a-heidelberg-fb-1',
    'Kreisklasse A Karlsruhe 1',
    'kreisklasse-a-karlsruhe-1-fb-1',
    'Kreisklasse A Karlsruhe 2',
    'kreisklasse-a-karlsruhe-2-fb-1',
    'Kreisklasse A Mannheim 1',
    'kreisklasse-a-mannheim-1-fb-1',
    'Kreisklasse A Mannheim 2',
    'kreisklasse-a-mannheim-2-fb-1',
    'Kreisklasse A Mosbach',
    'kreisklasse-a-mosbach-fb-1',
    'Kreisklasse A Pforzheim 1',
    'kreisklasse-a-pforzheim-1-fb-1',
    'Kreisklasse A Pforzheim 2',
    'kreisklasse-a-pforzheim-2-fb-1',
    'Kreisklasse A Sinsheim',
    'kreisklasse-a-sinsheim-fb-1',
    'Kreisklasse A Tauberbischofsheim',
    'kreisklasse-a-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse B',
    'Kreisklasse B Bruchsal Hardt',
    'kreisklasse-b-bruchsal-hardt-fb-1',
    'Kreisklasse B Bruchsal Kraichgau',
    'nordbaden-kk-b-bruchsal-fb-1',
    'Kreisklasse B Buchen',
    'nordbaden-kk-b-buchen-1-fb-1',
    'Kreisklasse B Heidelberg',
    'nordbaden-kk-b-heidelberg-fb-1',
    'Kreisklasse B Karlsruhe 1',
    'nordbaden-kkb-karlsruhe-1-fb-1',
    'Kreisklasse B Karlsruhe 2',
    'nordbaden-kkb-karlsruhe-2-fb-1',
    'Kreisklasse B Karlsruhe 3',
    'nordbaden-kkb-karlsruhe-3-fb-1',
    'Kreisklasse B Mannheim 1',
    'nordbaden-kk-b-mannheim-1-fb-1',
    'Kreisklasse B Mannheim 2',
    'nordbaden-kk-b-mannheim-2-fb-1',
    'Kreisklasse B Mannheim 3',
    'nordbaden-kk-a-mannheim-3-fb-1',
    'Kreisklasse B Mosbach 1',
    'nordbaden-kk-b-mosbach-1-fb-1',
    'Kreisklasse B Mosbach 2',
    'nordbaden-kk-b-mosbach-2-fb-1',
    'Kreisklasse B Pforzheim 1',
    'nordbaden-kk-b-pforzheim-1-fb-1',
    'Kreisklasse B Pforzheim 2',
    'nordbaden-kk-b-pforzheim-2-fb-1',
    'Kreisklasse B Sinsheim 1',
    'nordbaden-kk-b-sinsheim-1-fb-1',
    'Kreisklasse B Sinsheim 2',
    'nordbaden-kk-b-sinsheim-2-fb-1',
    'Kreisklasse B Tauberbischofsheim',
    'nordbaden-kk-b-tauberbischofsheim-fb-1'
  ],
  [
    'Baden',
    'Herren',
    'Kreisklasse C',
    'Kreisklasse C Heidelberg Ost',
    'nordbaden-kreisklasse-c-heidelberg-ost-6710',
    'Kreisklasse C Heidelberg West',
    'nordbaden-kreisklasse-c-heidelberg-west-6709',
    'Kreisklasse C Karlsruhe 1',
    'nordbaden-kreisklasse-c-karlsruhe-1-6713',
    'Kreisklasse C Karlsruhe 2',
    'nordbaden-kreisklasse-c-karlsruhe-2-6714',
    'Kreisklasse C Karlsruhe 3',
    'nordbaden-kreisklasse-c-karlsruhe-3-6715',
    'Kreisklasse C Karlsruhe 4',
    'nordbaden-kreisklasse-c-karlsruhe-4-6716',
    'Kreisklasse C Mannheim 1',
    'nordbaden-kreisklasse-c-mannheim-1-6711',
    'Kreisklasse C Pforzheim 1',
    'nordbaden-kreisklasse-c-pforzheim-1-6718',
    'Kreisklasse C Pforzheim 2',
    'nordbaden-kreisklasse-c-pforzheim-2-6719',
    'Kreisklasse C Pforzheim 3',
    'nordbaden-kreisklasse-c-pforzheim-3-6720',
    'Kreisklasse C Tauberbischofsheim',
    'nordbaden-kreisklasse-c-tauberbischofsheim-1-6721'
  ],
  [
    'Rheinland',
    'Herren',
    'Oberliga',
    'Oberliga Rheinland-Pfalz/Saar Abstiegsrunde',
    'oberliga-rheinland-pfalz-saar-abstiegsrunde',
    'Oberliga Rheinland-Pfalz/Saar Meisterrunde',
    'oberliga-rheinland-pfalz-saar-meisterrunde'
  ],
  [
    'Rheinland',
    'Herren',
    'Rheinlandliga',
    'rheinlandliga-fb-1',
  ],
  [
    'Rheinland',
    'Herren',
    'Bezirksliga',
    'Bezirksliga Mitte',
    'rheinland-bezirksliga-mitte-fb-1',
    'Bezirksliga Ost',
    'rheinland-bezirksliga-ost-fb-1',
    'Bezirksliga West',
    'rheinland-bezirksliga-west-fb-1',
  ],
  [
    'Rheinland',
    'Herren',
    'Kreisliga A',
    'Kreisliga A Eifel',
    'kreisliga-a-eifel-fb-1',
    'Kreisliga A Hunsrück/Mosel',
    'kreisliga-a-hunsrueckmosel-fb-1',
    'Kreisliga A Koblenz',
    'kreisliga-a-koblenz-fb-1',
    'Kreisliga A Mosel',
    'kreisliga-a-mosel-fb-1',
    'Kreisliga A Rhein/Ahr',
    'kreisliga-a-rheinahr-fb-1',
    'Kreisliga A Rhein/Lahn Meisterrunde',
    'ama_68406192',
    'Kreisliga A Rhein/Lahn Platzierungsrunde',
    'ama_68406592',
    'Kreisliga A Trier/Saarburg',
    'kreisliga-a-triersaarburg-fb-1',
    'Kreisliga A Westerwald/Sieg',
    'kreisliga-a-westerwaldsieg-fb-1',
    'Kreisliga A Westerwald/Wied',
    'kreisliga-a-westerwaldwied-fb-1'
  ],
  [
    'Rheinland',
    'Herren',
    'Kreisliga B',
    'Kreisliga B Ahr',
    'kreisliga-b-rheinahr-fb-1',
    'Kreisliga B Eifel 1',
    'kreisliga-b-eifel-1-fb-1',
    'Kreisliga B Eifel 2',
    'kreisliga-b-eifel-2-fb-1',
    'Kreisliga B Hunsrück/Mosel Nord',
    'kreisliga-b-hunsrueckmosel-nord-fb-1',
    'Kreisliga B Hunsrück/Mosel Süd',
    'kreisliga-b-hunsrueckmosel-sued-fb-1',
    'Kreisliga B Koblenz',
    'kreisliga-b-koblenz-fb-1',
    'Kreisliga B Mayen',
    'kreisliga-b-rheinmayen-fb-1',
    'Kreisliga B Mosel 1',
    'kreisliga-b-mosel-1-fb-1',
    'Kreisliga B Mosel 2',
    'kreisliga-b-mosel-2-fb-1',
    'Kreisliga B Mosel/Hochwald',
    'kreisliga-b-moselhochwald-fb-1',
    'Kreisliga B Rhein/Lahn',
    'kreisliga-b-rheinlahn-fb-1',
    'Kreisliga B Trier/Saar',
    'kreisliga-b-triersaarburg-fb-1',
    'Kreisliga B Westerwald/Sieg 1',
    'kreisliga-b-westerwaldsieg-1-fb-1',
    'Kreisliga B Westerwald/Sieg 2',
    'kreisliga-b-westerwaldsieg-2-fb-1',
    'Kreisliga B Westerwald/Wied Nord',
    'kreisliga-b-westerwaldwied-nord-fb-1',
    'Kreisliga B Westerwald/Wied Süd',
    'kreisliga-b-westerwaldwied-sued-fb-1'
  ],
  [
    'Rheinland',
    'Herren',
    'Kreisliga C',
    'Kreisliga C 2 Hunsrück/Mosel',
    'liga5088',
    'Kreisliga C Ahr',
    'rheinland-kl-c-ahr-fb-1',
    'Kreisliga C Eifel 1',
    'rheinland-kl-c-eifel-1-fb-1',
    'Kreisliga C Eifel 2',
    'rheinland-kl-c-eifel-2-fb-1',
    'Kreisliga C Hunsrück/Mosel Meisterrunde',
    'kreisliga-c-hunsrueck-mosel-meisterrunde',
    'Kreisliga C Hunsrück/Mosel Platzierungsrunde',
    'kreisliga-c-hunsrueck-mosel-platzierungsrunde',
    'Kreisliga C Koblenz',
    'rheinland-kl-c-koblenz-fb-1',
    'Kreisliga C Mayen',
    'rheinland-kl-c-mayen-fb-1',
    'Kreisliga C Mosel 1',
    'rheinland-kl-c-mosel-1-fb-1',
    'Kreisliga C Mosel 2',
    'rheinland-kl-c-mosel-2-fb-1',
    'Kreisliga C Mosel/Hochwald',
    'rheinland-kl-c-moselhochwald-fb-1',
    'Kreisliga C Rhein/Lahn',
    'klc-rheinlahn-fb-1',
    'Kreisliga C Saar',
    'rheinland-kl-c-saar-fb-1',
    'Kreisliga C Trier/Eifel',
    'rheinland-kl-c-triereifel-fb-1',
    'Kreisliga C Westerwald/Sieg 1',
    'rheinland-kl-c-westerwaldsieg-1-fb-1',
    'Kreisliga C Westerwald/Sieg 2',
    'rheinland-kl-c-westerwaldsieg-2-fb-1',
    'Kreisliga C Westerwald/Wied Nordwest',
    'rheinland-kl-c-westerwaldwied-nordwest-fb-1',
    'Kreisliga C Westerwald/Wied Südost',
    'rheinland-kl-c-westerwaldwied-suedost-fb-1'
  ],
  [
    'Rheinland',
    'Herren',
    'Kreisliga D',
    'Kreisliga D Eifel 1',
    'rheinland-kreisliga-d-eifel-1-6723',
    'Kreisliga D Eifel 2',
    'rheinland-kreisliga-d-eifel-2-6724',
    'Kreisliga D Eifel 3',
    'rheinland-kreisliga-d-eifel-3-6725',
    'Kreisliga D Eifel 4',
    'rheinland-kreisliga-d-eifel-4-6727',
    'Kreisliga D Koblenz 1',
    'rheinland-kreisliga-d-koblenz-1-6728',
    'Kreisliga D Koblenz 2',
    'rheinland-kreisliga-d-koblenz-2-6729',
    'Kreisliga D Koblenz 3',
    'rheinland-kreisliga-d-koblenz-3-6730',
    'Kreisliga D Mosel/Hochwald',
    'rheinland-kreisliga-d-moselhochwald-6736',
    'Kreisliga D Rhein/Ahr Nord',
    'rheinland-kreisliga-d-rheinahr-nord-6726',
    'Kreisliga D Rhein/Ahr Süd',
    'rheinland-kreisliga-d-rheinahr-sued-6722',
    'Kreisliga D Rhein/Lahn Meisterrunde',
    'ama_66026788',
    'Kreisliga D Rhein/Lahn Platzierungsrunde',
    'ama_66026848',
    'Kreisliga D Saar',
    'rheinland-kreisliga-d-saar-6734',
    'Kreisliga D Trier/Eifel',
    'rheinland-kreisliga-d-triereifel-6735',
    'Kreisliga D Westerwald Wied Nordwest Meisterrunde',
    'ama_68831092',
    'Kreisliga D Westerwald/Sieg 1',
    'rheinland-kreisliga-d-westerwaldsieg-1-6737',
    'Kreisliga D Westerwald/Sieg 2',
    'rheinland-kreisliga-d-westerwaldsieg-2-6738',
    'Kreisliga D Westerwald/Wied Platzierungsrunde',
    'ama_66026862',
    'Kreisliga D Westerwald/Wied Südost',
    'rheinland-kreisliga-d-westerwaldwied-suedost-6742'
  ],
  [
    'Südbaden',
    'Herren',
    'Oberliga',
    'Oberliga Baden-Württemberg',
    'oberliga-baden-wuerttemberg'
  ],
  [
    'Südbaden',
    'Herren',
    'Verbandsliga',
    'Verbandsliga Südbaden',
    'suedbaden-vl-fb-1'
  ],
  [
    'Südbaden',
    'Herren',
    'Landesliga',
    'Landesliga 1',
    'suedbaden-ll-1-fb-1',
    'Landesliga 2',
    'suedbaden-ll-2-fb-1',
    'Landesliga 3',
    'suedbaden-ll-3-fb-1'
  ],
  [
    'Südbaden',
    'Herren',
    'Bezirksliga',
    'Bezirksliga Baden-Baden',
    'bezirksliga-baden-baden-fb-1',
    'Bezirksliga Bodensee',
    'suedbaden-bezirksliga-sb-bodensee-fb-1',
    'Bezirksliga Freiburg',
    'bezirksliga-freiburg-fb-1',
    'Bezirksliga Hochrhein',
    'bezirksliga-hochrhein-fb-1',
    'Bezirksliga Offenburg',
    'bezirksliga-offenburg-fb-1',
    'Bezirksliga Schwarzwald',
    'suedbaden-bezirksliga-sb-schwarzwald-fb-1',
  ],
  [
    'Südbaden',
    'Herren',
    'Kreisliga A',
    'Kreisliga A Baden-Baden Nord',
    'kreisliga-a-baden-baden-nord-fb-1',
    'Kreisliga A Baden-Baden Süd',
    'kreisliga-a-baden-baden-sued-fb-1',
    'Kreisliga A Bodensee 1',
    'suedbaden-kreisliga-a-sb-bodensee-1-fb-1',
    'Kreisliga A Bodensee 2',
    'suedbaden-kreisliga-a-sb-bodensee-2-fb-1',
    'Kreisliga A Bodensee 3',
    'suedbaden-kreisliga-a-sb-bodensee-3-fb-1',
    'Kreisliga A Freiburg 1',
    'kreisliga-a-freiburg-1-fb-1',
    'Kreisliga A Freiburg 2',
    'kreisliga-a-freiburg-2-fb-1',
    'Kreisliga A Hochrhein Ost',
    'kreisliga-a-hochrhein-3-fb-1',
    'Kreisliga A Hochrhein West',
    'kreisliga-a-hochrhein-1-fb-1',
    'Kreisliga A Offenburg Nord',
    'kreisliga-a-offenburg-nord-fb-1',
    'Kreisliga A Offenburg Süd',
    'kreisliga-a-offenburg-sued-fb-1',
    'Kreisliga A Schwarzwald 1',
    'suedbaden-kreisliga-a-sb-schwarzwald-1-fb-1',
    'Kreisliga A Schwarzwald 2',
    'suedbaden-kreisliga-a-sb-schwarzwald-2-fb-1',
  ],
  [
    'Südbaden',
    'Herren',
    'Kreisliga B',
    'Kreisliga B Baden-Baden 1',
    'suedbaden-klb-baden-baden-1-fb-1',
    'Kreisliga B Baden-Baden 4',
    'suedbaden-klb-baden-baden-4-fb-1',
    'Kreisliga B Baden-Baden 5',
    'suedbaden-klb-baden-baden-5-fb-1',
    'Kreisliga B Bodensee 1',
    'suedbaden-kl-b-bodensee-1-fb-1',
    'Kreisliga B Bodensee 2',
    'suedbaden-kl-b-bodensee-2-fb-1',
    'Kreisliga B Bodensee 3',
    'suedbaden-kl-b-bodensee-3-fb-1',
    'Kreisliga B Bodensee 4',
    'suedbaden-kl-b-bodensee-4-fb-1',
    'Kreisliga B Freiburg 1',
    'suedbaden-klb-freiburg-1-fb-1',
    'Kreisliga B Freiburg 2',
    'suedbaden-klb-freiburg-2-fb-1',
    'Kreisliga B Freiburg 3',
    'suedbaden-klb-freiburg-3-fb-1',
    'Kreisliga B Freiburg 4',
    'suedbaden-klb-freiburg-4-fb-1',
    'Kreisliga B Freiburg 5',
    'suedbaden-klb-freiburg-5-fb-1',
    'Kreisliga B Freiburg 6',
    'suedbaden-klb-freiburg-6-fb-1',
    'Kreisliga B Freiburg 7',
    'suedbaden-klb-freiburg-7-fb-1',
    'Kreisliga B Hochrhein 1',
    'suedbaden-kl-b-hochrhein-1-fb-1',
    'Kreisliga B Hochrhein 2',
    'suedbaden-kl-b-hochrhein-2-fb-1',
    'Kreisliga B Hochrhein 3',
    'suedbaden-kl-b-hochrhein-3-fb-1',
    'Kreisliga B Hochrhein 4',
    'suedbaden-kl-b-hochrhein-4-fb-1',
    'Kreisliga B Offenburg 1',
    'suedbaden-kl-b-offenburg-1-fb-1',
    'Kreisliga B Offenburg 2',
    'suedbaden-kl-b-offenburg-2-fb-1',
    'Kreisliga B Offenburg 3',
    'suedbaden-kl-b-offenburg-3-fb-1',
    'Kreisliga B Offenburg 4',
    'suedbaden-kl-b-offenburg-4-fb-1',
    'Kreisliga B Offenburg 6',
    'suedbaden-kl-b-offenburg-6-fb-1',
    'Kreisliga B Offenburg 7',
    'suedbaden-kl-b-offenburg-7-fb-1',
    'Kreisliga B Offenburg 8',
    'suedbaden-kl-b-offenburg-8-fb-1',
    'Kreisliga B Schwarzwald 1',
    'suedbaden-kl-b-schwarzwald-1-fb-1',
    'Kreisliga B Schwarzwald 2',
    'suedbaden-kl-b-schwarzwald-2-fb-1',
    'Kreisliga B Schwarzwald 3',
    'suedbaden-kl-b-schwarzwald-3-fb-1',
    'Kreisliga B Schwarzwald 4',
    'suedbaden-kl-b-schwarzwald-4-fb-1',
    'Kreisliga B Schwarzwald 5',
    'suedbaden-kl-b-schwarzwald-5-fb-1',
    'Kreisliga B Schwarzwald 6',
    'suedbaden-kl-b-schwarzwald-6-fb-1',
  ],
  [
    'Südbaden',
    'Herren',
    'Kreisliga C',
    'Kreisliga C Baden-Baden 1',
    'suedbaden-kreisliga-c-baden-baden-1-6799',
    'Kreisliga C Baden-Baden 2',
    'suedbaden-kreisliga-c-baden-baden-2-6803',
    'Kreisliga C Baden-Baden 5',
    'kreisliga-c-baden-baden-5-fb-1',
    'Kreisliga C Baden-Baden 6',
    'kreisliga-c-baden-baden-6-fb-1',
    'Kreisliga C Bodensee 1',
    'suedbaden-kreisliga-c-bodensee-1-6804',
    'Kreisliga C Bodensee 2',
    'suedbaden-kreisliga-c-bodensee-2-6805',
    'Kreisliga C Bodensee 3',
    'suedbaden-kreisliga-c-bodensee-3-6806',
    'Kreisliga C Bodensee 4',
    'suedbaden-kreisliga-c-bodensee-4-6807',
    'Kreisliga C Freiburg 1',
    'suedbaden-kreisliga-c-freiburg-1-6800',
    'Kreisliga C Freiburg 2',
    'suedbaden-kreisliga-c-freiburg-2-6801',
    'Kreisliga C Freiburg 3',
    'suedbaden-kreisliga-c-freiburg-3-6802',
    'Kreisliga C Freiburg 4',
    'suedbaden-kreisliga-c-freiburg-4-6834',
    'Kreisliga C Hochrhein 1',
    'suedbaden-kreisliga-c-hochrhein-1-6835',
    'Kreisliga C Hochrhein 2',
    'suedbaden-kreisliga-c-hochrhein-2-6836',
    'Kreisliga C Hochrhein 3',
    'suedbaden-kreisliga-c-hochrhein-3-6837',
    'Kreisliga C Hochrhein 4',
    'suedbaden-kreisliga-c-hochrhein-4-6838',
    'Kreisliga C Hochrhein 5',
    'suedbaden-kreisliga-c-hochrhein-5-6839',
    'Kreisliga C Hochrhein 6',
    'suedbaden-kreisliga-c-hochrhein-6-6843',
    'Kreisliga C Offenburg 1',
    'suedbaden-kreisliga-c-offenburg-1-6830',
    'Kreisliga C Offenburg 2',
    'suedbaden-kreisliga-c-offenburg-2-6831',
    'Kreisliga C Offenburg 3',
    'suedbaden-kreisliga-c-offenburg-3-6832',
    'Kreisliga C Offenburg 4',
    'suedbaden-kreisliga-c-offenburg-4-6833',
    'Kreisliga C Schwarzwald 1',
    'suedbaden-kreisliga-c-schwarzwald-1-6840',
    'Kreisliga C Schwarzwald 2',
    'suedbaden-kreisliga-c-schwarzwald-2-6841',
    'Kreisliga C Schwarzwald 3',
    'suedbaden-kreisliga-c-schwarzwald-3-6842'
  ],
];
